os: linux
dist: bionic
language: java
jdk:
  - openjdk8
before_install:
  - echo java is in $JAVA_HOME
install: 
  # sudo ./travis/install-oneapi.sh
  - ./travis/config-ssh.sh
  - ./travis/spark-cluster/setup-cluster.sh
  - ./travis/python/setup-python3-env.sh
before_script:
script:
  # - sudo ./travis/pyspark-pi.sh
  - ./travis/pyspark-kmeans.sh
  - echo SUCCESS
