sudo: required
dist: bionic
language: java
jdk:
  - openjdk8
python:
  - "3.6"
before_install:
  - echo $JAVA_HOME
  - python --version
install: 
  # sudo ./travis/install-oneapi.sh
  - sudo ./travis/config-ssh.sh
  - sudo ./travis/spark-cluster/setup-cluster.sh
  - sudo ./travis/python/setup-env.sh
before_script:
script:
  - cd $SPARK_HOME
  - sudo ./bin/spark-submit examples/src/main/python/pi.py
  - echo SUCCESS
